// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Boot(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function Disconnect():Promise<void>;

export function LoadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SendMessage(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;

export function ToggleGoDeaf():Promise<void>;

export function ToggleGoMute():Promise<void>;

export function UpdateCallID(arg1:string):Promise<void>;
