// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Boot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Boot'](arg1, arg2, arg3, arg4);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function ToggleGoDeaf() {
  return window['go']['main']['App']['ToggleGoDeaf']();
}

export function ToggleGoMute() {
  return window['go']['main']['App']['ToggleGoMute']();
}

export function UpdateCallID(arg1) {
  return window['go']['main']['App']['UpdateCallID'](arg1);
}
